# Streamlit Secrets Template
# Instructions:
# 1. Copy this file to .streamlit/secrets.toml
# 2. Fill in your API keys
# 3. Do not commit secrets.toml to version control

# OpenAI API key for GPT models
[openai]
api_key = "your-openai-api-key-here"

# DeepL API key for DeepL translation
[deepl]
api_key = "your-deepl-api-key-here"

# xAI API key for Grok models
[xai]
api_key = "your-xai-api-key-here"

# Custom settings (optional)
[settings]
default_model = "gpt-3.5-turbo"
default_pdf_mode = "markdown"
max_upload_size_mb = 15
enable_ocr = true 